import { StyleSheet, Dimensions, Platform } from 'react-native';

const { width, height } = Dimensions.get('window');

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#121212',
  },
  mapContainer: {
    flex: 3,
    backgroundColor: '#ccc',
  },
  map: {
    flex: 1,
  },
  bottomSectionContainer: {
    flex: Platform.OS === 'ios' ? 1.2 : 1.3,
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: Platform.OS === 'ios' ? 24 : 12,
    justifyContent: 'space-between',
    borderTopWidth: 1,
    borderTopColor: '#333',
    minHeight: 180,
  },
  header: {
    fontSize: 28,
    fontWeight: '700',
    color: '#fff',
    textAlign: 'center',
    marginVertical: 15,
  },
  errorContainer: {
    backgroundColor: 'rgba(255, 69, 0, 0.3)',
    paddingVertical: 6,
    paddingHorizontal: 10,
    marginHorizontal: 10,
    marginTop: 5,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
  },
  errorText: {
    color: '#FF4500',
    fontSize: 14,
    fontWeight: '500',
    flex: 1,
  },
  errorCloseButtonText: {
    color: '#FF4500',
    fontSize: 18,
    fontWeight: 'bold',
  },
  refreshButton: {
    position: 'absolute',
    bottom: 20,
    right: 20,
    backgroundColor: '#1E88E5',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 20,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.35,
    shadowRadius: 3,
  },
  refreshButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
  },

  // ==== Slimmer pill-style extra buttons ====
  extraButtonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 8,
  },
  extraButton: {
    flex: 1,
    marginHorizontal: 5,
    paddingVertical: 10,
    borderRadius: 25,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3,
  },
  // variants
  dashboardButton: { backgroundColor: '#6200EE' },
  reportButton:    { backgroundColor: '#03DAC6' },
  myReportsButton:{ backgroundColor: '#FB8C00' },
  logoutButton:    { backgroundColor: '#B00020' },

  extraButtonText: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '600',
  },

  emailContainer: {
    paddingVertical: 6,
    alignItems: 'center',
  },
  emailText: {
    color: '#aaa',
    fontSize: 12,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#1a1a1a',
  },
  loadingText: {
    fontSize: 18,
    color: '#fff',
    marginBottom: 15,
  },
  retryButton: {
    backgroundColor: '#1e90ff',
    paddingVertical: 12,
    paddingHorizontal: 25,
    borderRadius: 8,
    marginTop: 20,
  },
  retryButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  modalOverlay: {
    position: 'absolute',
    top: 0, left: 0, right: 0, bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 10,
  },
  modalContainer: {
    backgroundColor: '#333333',
    borderRadius: 16,
    paddingHorizontal: 20,
    paddingTop: 15,
    paddingBottom: 15,
    width: '95%',
    maxWidth: 500,
    maxHeight: height * 0.85,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.7,
    shadowRadius: 10,
    elevation: 10,
    position: 'relative',
  },
  modalTopCloseButton: {
    position: 'absolute',
    top: 8, right: 8,
    padding: 8,
    zIndex: 10,
  },
  modalTopCloseButtonText: {
    color: '#ccc',
    fontSize: 24,
    fontWeight: 'bold',
    lineHeight: 24,
  },
  modalHeader: {
    fontSize: 22,
    fontWeight: '700',
    marginTop: 25,
    marginBottom: 15,
    color: '#f0f0f0',
    textAlign: 'center',
  },
  modalText: {
    fontSize: 15,
    marginBottom: 8,
    textAlign: 'center',
    color: '#cccccc',
    lineHeight: 21,
  },
  modalTextHighlight: {
    color: '#fff',
    fontWeight: '600',
  },

  priorityTextLow:    { color: '#ffeb3b' },
  priorityTextMedium: { color: '#ff9800' },
  priorityTextHigh:   { color: '#f44336' },

  paginationText: {
    fontSize: 12,
    color: '#aaa',
    marginBottom: 10,
    fontWeight: '500',
  },
  evidenceSection: {
    width: '100%',
    alignItems: 'center',
    marginVertical: 10,
    paddingTop: 15,
    borderTopWidth: 1,
    borderTopColor: '#555',
  },
  evidenceButton: {
    backgroundColor: '#007AFF',
    paddingVertical: 10,
    paddingHorizontal: 25,
    borderRadius: 25,
    marginVertical: 10,
  },
  evidenceButtonText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '500',
  },
  imageFrame: {
    borderWidth: 1,
    borderColor: '#666',
    borderRadius: 12,
    padding: 5,
    backgroundColor: '#2a2a2a',
    marginVertical: 10,
    width: '90%',
    aspectRatio: 16 / 9,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  evidencePreview: {
    borderRadius: 8,
    width: '100%',
    height: '100%',
  },
  noPhotoContainer: {
    width: '90%',
    aspectRatio: 16 / 9,
    backgroundColor: '#404040',
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  noPhotoText: {
    color: '#999',
    fontSize: 16,
    fontStyle: 'italic',
  },
  photoActionContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '90%',
    marginTop: 8,
  },
  modalButton: {
    borderRadius: 8,
    marginVertical: 4,
    paddingVertical: 10,
    paddingHorizontal: 15,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 40,
  },
  submitButton: { backgroundColor: '#4CAF50' },
  changeButton: { backgroundColor: '#ff9800' },
  removeButton: { backgroundColor: '#f44336' },
  modalButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
  },
  modalFooterContainer: {
    width: '100%',
    marginTop: 15,
    paddingTop: 15,
    borderTopWidth: 1,
    borderTopColor: '#555',
    alignItems: 'center',
    paddingBottom: 5,
  },
  modalNavContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
  },
  navButton: {
    backgroundColor: '#607d8b',
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 8,
    minWidth: 80,
    alignItems: 'center',
  },
  navButtonDisabled: {
    backgroundColor: '#444',
    opacity: 0.7,
  },
  navButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
  },
  cleanButton: {
    backgroundColor: '#4CAF50',
    paddingVertical: 10,
    paddingHorizontal: 18,
    borderRadius: 8,
    marginHorizontal: 10,
  },

  priorityModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  priorityModalContainer: {
    backgroundColor: '#333333',
    borderRadius: 16,
    paddingVertical: 30,
    paddingHorizontal: 25,
    width: '85%',
    maxWidth: 380,
    alignItems: 'stretch',
    elevation: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.5,
    shadowRadius: 6,
  },
  priorityModalHeader: {
    fontSize: 22,
    fontWeight: '600',
    marginBottom: 30,
    color: '#f0f0f0',
    textAlign: 'center',
  },
  scanButton: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    backgroundColor: '#FFD54F',
    borderRadius: 20,
    marginLeft: 8,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3,
  },
  scanButtonText: {
    color: '#121212',
    fontSize: 13,
    fontWeight: '600',
  },
  priorityButton: {
    paddingVertical: 16,
    borderRadius: 10,
    marginBottom: 18,
    alignItems: 'center',
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.3,
    shadowRadius: 2,
  },
  lowPriority: { backgroundColor: '#ffeb3b' },
  mediumPriority: { backgroundColor: '#ff9800' },
  highPriority: { backgroundColor: '#f44336' },
  cancelButton: { backgroundColor: '#6c757d', marginTop: 10 },
  priorityButtonText: {
    color: '#000',
    fontSize: 17,
    fontWeight: '600',
  },

  customMarker: {},
  markerImage: {},
});
