import { StyleSheet, Dimensions, Platform } from 'react-native';

const { width, height } = Dimensions.get('window');

export default StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: 'column',
    backgroundColor: '#121212',
  },
  mapContainer: {
    flex: 3,
    backgroundColor: '#ccc',
  },
  map: {
    flex: 1,
  },
  bottomSectionContainer: {
    flex: Platform.OS === 'ios' ? 1.2 : 1.3,
    paddingHorizontal: 15,
    paddingTop: 10,
    paddingBottom: Platform.OS === 'ios' ? 20 : 10,
    justifyContent: 'space-between',
    borderTopWidth: 1,
    borderTopColor: '#333',
    minHeight: 180,
  },
  header: {
    fontSize: 28,
    fontWeight: '700',
    color: '#fff',
    textAlign: 'center',
    marginVertical: 15,
  },
  errorContainer: {
    backgroundColor: 'rgba(255, 69, 0, 0.3)',
    paddingVertical: 8,
    paddingHorizontal: 12,
    marginHorizontal: 10,
    marginTop: 5,
    borderRadius: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  errorText: {
    color: '#FF4500',
    fontSize: 14,
    fontWeight: '500',
    flex: 1,
    textAlign: 'left',
  },
  errorCloseButton: {
    paddingLeft: 10,
  },
  errorCloseButtonText: {
    color: '#FF4500',
    fontSize: 18,
    fontWeight: 'bold',
  },
  refreshButton: {
    position: 'absolute',
    bottom: 15,
    right: 15,
    backgroundColor: 'rgba(30,144,255, 0.85)',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 20,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.3,
    shadowRadius: 2,
    zIndex: 5,
  },
  refreshButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
  },
  clusterContainer: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(0, 0, 0, 0.75)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.5)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.4,
    shadowRadius: 2,
    elevation: 4,
  },
  clusterText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  deviceStatusContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 5,
    marginBottom: 5,
  },
  deviceStatusText: {
    fontSize: 14,
    fontWeight: '600',
    marginRight: 8,
  },
  rescanButton: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    backgroundColor: '#444',
    borderRadius: 15,
  },
  rescanButtonText: {
    color: '#eee',
    fontSize: 12,
  },
  extraButtonContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-around',
    paddingVertical: 5,
    marginBottom: 5,
  },
  extraButton: {
    paddingVertical: 10,
    paddingHorizontal: 12,
    backgroundColor: '#4b4b4b',
    borderRadius: 25,
    marginBottom: 8,
    minWidth: width / 4.8,
    alignItems: 'center',
    marginHorizontal: 2,
  },
  extraButtonText: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '600',
    textAlign: 'center',
  },
  emailContainer: {
    paddingVertical: 5,
    alignItems: 'center',
  },
  emailText: {
    color: '#aaa',
    fontSize: 12,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#1a1a1a',
  },
  loadingText: {
    fontSize: 18,
    color: '#fff',
    marginBottom: 15,
  },
  retryButton: {
    backgroundColor: '#1e90ff',
    paddingVertical: 12,
    paddingHorizontal: 25,
    borderRadius: 8,
    marginTop: 20,
  },
  retryButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  modalOverlay: {
    position: 'absolute',
    top: 0, left: 0, right: 0, bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 10,
  },
  modalContainer: {
    backgroundColor: '#333333',
    borderRadius: 16,
    paddingHorizontal: 20,
    paddingTop: 15,
    paddingBottom: 15,
    width: '95%',
    maxWidth: 500,
    maxHeight: height * 0.85,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.7,
    shadowRadius: 10,
    elevation: 10,
    position: 'relative',
  },
  modalTopCloseButton: {
    position: 'absolute',
    top: 8,
    right: 8,
    padding: 8,
    zIndex: 10,
  },
  modalTopCloseButtonText: {
    color: '#ccc',
    fontSize: 24,
    fontWeight: 'bold',
    lineHeight: 24,
  },
  modalHeader: {
    fontSize: 22,
    fontWeight: '700',
    marginTop: 25,
    marginBottom: 15,
    color: '#f0f0f0',
    textAlign: 'center',
  },
  modalText: {
    fontSize: 15,
    marginBottom: 8,
    textAlign: 'center',
    color: '#cccccc',
    lineHeight: 21,
  },
  modalTextHighlight: {
    color: '#fff',
    fontWeight: '600',
  },
  priorityTextLow: { color: '#ffeb3b' },
  priorityTextMedium: { color: '#ff9800' },
  priorityTextHigh: { color: '#f44336' },
  paginationText: {
    fontSize: 12,
    color: '#aaa',
    marginBottom: 10,
    fontWeight: '500',
  },
  evidenceSection: {
    width: '100%',
    alignItems: 'center',
    marginVertical: 10,
    paddingTop: 15,
    borderTopWidth: 1,
    borderTopColor: '#555',
  },
  evidenceButton: {
    backgroundColor: '#007AFF',
    paddingVertical: 10,
    paddingHorizontal: 25,
    borderRadius: 25,
    marginVertical: 10,
  },
  evidenceButtonText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '500',
  },
  imageFrame: {
    borderWidth: 1,
    borderColor: '#666',
    borderRadius: 12,
    padding: 5,
    backgroundColor: '#2a2a2a',
    marginBottom: 12,
    marginTop: 8,
    width: '90%',
    aspectRatio: 16/9,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  evidencePreview: {
    borderRadius: 8,
    width: '100%',
    height: '100%',
  },
  noPhotoContainer: {
    width: '90%',
    aspectRatio: 16/9,
    backgroundColor: '#404040',
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
    marginTop: 8,
  },
  noPhotoText: {
    color: '#999',
    fontSize: 16,
    fontStyle: 'italic',
  },
  photoActionContainer: {
      flexDirection: 'row',
      justifyContent: 'space-around',
      width: '90%',
      marginTop: 8,
  },
  modalButton: {
    borderRadius: 8,
    marginVertical: 4,
    paddingVertical: 10,
    paddingHorizontal: 15,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 40,
  },
  submitButton: { backgroundColor: '#4CAF50' },
  changeButton: { backgroundColor: '#ff9800' },
  removeButton: { backgroundColor: '#f44336' },
  modalButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
    textAlign: 'center',
  },
  modalFooterContainer: {
    width: '100%',
    marginTop: 15,
    paddingTop: 15,
    borderTopWidth: 1,
    borderTopColor: '#555',
    alignItems: 'center',
    paddingBottom: 5,
  },
  modalNavContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    alignItems: 'center',

  },
  navButton: {
    backgroundColor: '#607d8b',
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 8,
    minWidth: 80,
    alignItems: 'center',
  },
  navButtonDisabled: {
    backgroundColor: '#444',
    opacity: 0.7,
  },
  navButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
  },
  cleanButton: {
    backgroundColor: '#4CAF50',
    paddingVertical: 10,
    paddingHorizontal: 18,
    borderRadius: 8,
    marginHorizontal: 10,
  },

  priorityModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  priorityModalContainer: {
    backgroundColor: '#333333',
    borderRadius: 16,
    paddingVertical: 30,
    paddingHorizontal: 25,
    width: '85%',
    maxWidth: 380,
    alignItems: 'stretch',
    elevation: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.5,
    shadowRadius: 6,
  },
  priorityModalHeader: {
    fontSize: 22,
    fontWeight: '600',
    marginBottom: 30,
    color: '#f0f0f0',
    textAlign: 'center',
  },
  priorityButton: {
    paddingVertical: 16,
    borderRadius: 10,
    marginBottom: 18,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.3,
    shadowRadius: 2,
    elevation: 3,
  },
  lowPriority: { backgroundColor: '#ffeb3b' },
  mediumPriority: { backgroundColor: '#ff9800' },
  highPriority: { backgroundColor: '#f44336' },
  cancelButton: { backgroundColor: '#6c757d', marginTop: 10 },
  priorityButtonText: {
    color: '#000',
    fontSize: 17,
    fontWeight: '600',
  },
  customMarker: {  },
  markerImage: {  },
});