import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export default StyleSheet.create({
  // Layout
  container: {
    flex: 1,
    flexDirection: 'column',
    backgroundColor: '#121212',
  },
  mapContainer: {
    flex: 3,
    backgroundColor: '#ccc',
  },
  map: {
    flex: 1,
  },
  bottomSectionContainer: {
    flex: 1,
    paddingHorizontal: 15,
    paddingVertical: 5,
    justifyContent: 'space-around',
  },

  // Components
  header: {
    fontSize: 28,
    fontWeight: '700',
    color: '#fff',
    textAlign: 'center',
    marginVertical: 15,
  },
  errorContainer: {
    backgroundColor: 'rgba(255, 0, 0, 0.2)',
    padding: 10,
    borderRadius: 8,
    marginHorizontal: 15,
    marginTop: 5,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  errorText: {
    color: 'red',
    fontSize: 14,
    flex: 1,
    textAlign: 'left',
  },
  errorCloseButton: {
    paddingLeft: 10,
  },
  errorCloseButtonText: {
    color: 'red',
    fontSize: 18,
    fontWeight: 'bold',
  },
  refreshButton: {
    position: 'absolute',
    bottom: 15,
    right: 15,
    backgroundColor: 'rgba(30,144,255,0.9)',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 20,
    elevation: 3,
    zIndex: 5,
  },
  refreshButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
  },
  deviceStatusContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 5,
    borderRadius: 20,
  },
  deviceStatusText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#fff',
    marginRight: 8,
  },
  rescanButton: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    backgroundColor: '#444',
    borderRadius: 4,
  },
  rescanButtonText: {
    color: '#eee',
    fontSize: 12,
  },
  extraButtonContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-around',
    paddingVertical: 5,
  },
  extraButton: {
    paddingVertical: 10,
    paddingHorizontal: 15,
    backgroundColor: '#4b4b4b',
    borderRadius: 25,
    marginBottom: 8,
    minWidth: width / 4.8,
    alignItems: 'center',
  },
  manualButton: {
    // if needed
  },
  extraButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
    textAlign: 'center',
  },
  emailContainer: {
    paddingVertical: 5,
    borderRadius: 20,
    alignItems: 'center',
  },
  emailText: {
    color: '#ccc',
    fontSize: 12,
  },

  // Miscellaneous
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#1a1a1a',
  },
  loadingText: {
    fontSize: 18,
    color: '#fff',
    marginBottom: 10,
  },
  retryButton: {
    backgroundColor: '#1e90ff',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 8,
    marginTop: 15,
  },
  retryButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  modalOverlay: {
    position: 'absolute',
    top: 0, left: 0, right: 0, bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 10,
  },
  modalContainer: {
    backgroundColor: '#2c2c2c',
    borderRadius: 14,
    paddingHorizontal: 15,
    paddingVertical: 6,
    width: '95%',
    maxWidth: 480,
    maxHeight: '90%',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.6,
    shadowRadius: 8,
    elevation: 8,
  },
  modalHeader: {
    fontSize: 19,
    fontWeight: '700',
    marginBottom: 6,
    color: '#eaeaea',
    textAlign: 'center',
  },
  modalText: {
    fontSize: 13,
    marginBottom: 4,
    textAlign: 'center',
    color: '#b5b5b5',
    lineHeight: 17,
  },
  modalTextHighlight: {
    color: '#fff',
    fontWeight: '600',
  },
  priorityTextLow: { color: '#ffff00' },
  priorityTextMedium: { color: '#ffa500' },
  priorityTextHigh: { color: '#ff4500' },
  paginationText: {
    fontSize: 10,
    color: '#999',
    marginBottom: 5,
  },
  evidenceSection: {
    width: '100%',
    alignItems: 'center',
    marginVertical: 4,
  },
  evidenceButton: {
    backgroundColor: '#0077ff',
    paddingVertical: 7,
    paddingHorizontal: 16,
    borderRadius: 18,
    marginVertical: 4,
  },
  evidenceButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '500',
  },
  imageFrame: {
    borderWidth: 1,
    borderColor: '#555',
    borderRadius: 10,
    padding: 3,
    backgroundColor: '#1f1f1f',
    marginBottom: 6,
    marginTop: 3,
    width: '85%',
    aspectRatio: 1,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  evidencePreview: {
    borderRadius: 7,
    width: '100%',
    height: '100%',
  },
  noPhotoContainer: {
    width: '85%',
    aspectRatio: 1,
    backgroundColor: '#333',
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 6,
    marginTop: 3,
  },
  noPhotoText: {
    color: '#888',
    fontSize: 14,
  },
  submitButton: { backgroundColor: '#4CAF50' },
  changeButton: { backgroundColor: '#ff9800' },
  removeButton: { backgroundColor: '#f44336' },
  modalNavContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    marginTop: 6,
    alignItems: 'center',
    marginBottom: 4,
  },
  navButton: {
    backgroundColor: '#555',
    paddingVertical: 8,
    paddingHorizontal: 15,
    borderRadius: 18,
  },
  navButtonDisabled: {
    backgroundColor: '#333',
    opacity: 0.6,
  },
  navButtonText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: 'bold',
  },
  cleanButton: {
    backgroundColor: '#4CAF50',
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 7,
  },
  closeButton: {
    backgroundColor: '#f44336',
    marginTop: 6,
    paddingVertical: 8,
    paddingHorizontal: 30,
    borderRadius: 18,
  },
  modalButton: {
    borderRadius: 7,
    marginVertical: 3,
    paddingVertical: 8,
    paddingHorizontal: 12,
    alignItems: 'center',
  },
  modalButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
    textAlign: 'center',
  },

  // Priority Modal
  priorityModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  priorityModalContainer: {
    backgroundColor: '#2c2c2c',
    borderRadius: 16,
    paddingVertical: 25,
    paddingHorizontal: 20,
    width: '80%',
    maxWidth: 350,
    alignItems: 'stretch',
    elevation: 10,
  },
  priorityModalHeader: {
    fontSize: 20,
    fontWeight: '600',
    marginBottom: 20,
    color: '#eaeaea',
    textAlign: 'center',
  },
  priorityButton: {
    paddingVertical: 14,
    borderRadius: 8,
    marginBottom: 12,
    alignItems: 'center',
  },
  lowPriority: { backgroundColor: '#ffc107' },
  mediumPriority: { backgroundColor: '#ff9800' },
  highPriority: { backgroundColor: '#f44336' },
  cancelButton: { backgroundColor: '#607d8b', marginTop: 5 },
  priorityButtonText: {
    color: '#000',
    fontSize: 16,
    fontWeight: '600',
  },

  // Marker Styles
  customMarker: {
    width: 30,
    height: 30,
    borderRadius: 15,
    justifyContent: 'center',
    alignItems: 'center',
  },
  markerImage: {
    width: 30,
    height: 30,
    resizeMode: 'contain',
  },
});
